services:
  - type: web
    name: Zoom Video SDK Auth Sample
    runtime: node
    buildCommand: npm install express axios crypto dotenv
    startCommand: npm start
    repo: https://github.com/zoom/webhook-sample
    rootDir: .
    plan: free
    envVars:
      - key: ZOOM_WEBHOOK_SECRET_TOKEN
        sync: false
      - key: N8N_WEBHOOK_URL
        value: https://n8n.crogallcapital.com/webhook/zoom-webinar-ended
        sync: false
